<?php
return [
'articleimagedir' => 'uploads/article/',
'articleimagethambtdir' => 'uploads/article/articlethamb/',
'articleimagemediumdir' => 'uploads/article/articlemediumimage/',
'articleimagelargedir' => 'uploads/article/articlelargeimage/',
'articleimageextralargedir' => 'uploads/article/articleextralargeimage/',
'quickbytesimageextralargedir' => 'uploads/quickbyte/quickbytesextralargeimage/',
'quickbytesimagemediumdir' =>'uploads/quickbyte/quickbytesmediumimage/',
'quickbytesimagethambtdir' => 'uploads/quickbyte/quickbytesthamb/',
'quickbyteimagedir' => 'uploads/quickbyte/',
'albumimagedir' => 'uploads/album/', 
'awarticleimagedir' => 'article/',
'awarticleimagethumbtdir' => 'article/article_thumb/',
'awarticleimagemediumdir' => 'article/article_medium_image/',
'awarticleimagelargedir' => 'article/article_large_image/',
'awarticleimageextralargedir' => 'article/article_extra_large_image/',
'awquickbyteimagedir' => 'quickbyte/',  
'awquickbytesimagethumbtdir' => 'quickbyte/quickbytes_thumb/',
'awquickbytesimagemediumdir' =>'quickbyte/quickbytes_medium_image/',
'awquickbytesimageextralargedir' => 'quickbyte/quickbytes_extralarge_image/',
'awalbumimagedir' => 'album/', 
'awauthordir'=> 'author/', 
'awaevent'=> 'event/',
'awatipstag'=> 'tipstag/',
'awfeaturebox'=>'featurebox/',   
'awbucket'=>'bwmedia',
'awsbaseurl'=>'https://s3-ap-southeast-1.amazonaws.com/bwmedia/',    
'recordperpage' => '10'    
];
?>
